# Generated by Django 5.2.2 on 2025-06-05 00:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
